In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

Call the dataframe that contains the processed text data including stopwords removal, lemmatization 

In [2]:
# dataset of stacked responses
mstack = pd.read_json("~/thesis/data/processed_uscensus/political_mentions_stack.jsonl", orient = "records", lines = True)

In [3]:
# dataset of each responses
m1 = pd.read_json("~/thesis/data/processed_uscensus/political_mention1.jsonl", orient = "index")
m2 = pd.read_json("~/thesis/data/processed_uscensus/political_mention2.jsonl", orient = "index")
m3 = pd.read_json("~/thesis/data/processed_uscensus/political_mention3.jsonl", orient = "index")

## Participant-based analysis
### 1. Dataset: concatenated texts from the mention 1,2,3 

In [4]:
mconcat = pd.read_json("~/thesis/data/processed_uscensus/political_mentions.jsonl", orient = 'index')

In [5]:
mconcat

mentions
200015            racim blacks whites false information  
200022                          coming together country  
200039  severe political polarization allow compromise...
200046  pandemic covid 19 unemployment lot people loss...
200053  globalism fake covid law order blm public educ...
...                                                   ...
535315         unity people harming coming together one  
535360  divisiveness divided unified race inequality p...
535414  health immigration way separate families globa...
535421  bias main stream media border control illegal ...
535469  pandemic totally control equapilty issue racia...

[7298 rows x 1 columns]

In [6]:
documents = mconcat['mentions'].to_list()

In [7]:
# Create a Bag of Words model
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(documents)

# Convert to array to see the result
X_array = X.toarray()

# Feature names (words)
features = vectorizer.get_feature_names_out()

print(features)
print(X_array)

['00' '000' '04' ... 'zilch' 'zombie' 'zone']
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [8]:
from sklearn.cluster import KMeans

# Apply KMeans clustering
n_clusters = 2  # Example: trying to find 3 clusters
kmeans = KMeans(n_clusters=n_clusters, random_state=0)
kmeans.fit(X_array)

# Get cluster labels
labels = kmeans.labels_

print(labels)


[0 0 0 ... 0 0 1]


In [9]:
from sklearn.metrics import silhouette_score

# Calculate the silhouette score
sil_score = silhouette_score(X_array, labels)
print(f"Silhouette Score: {sil_score}")


Silhouette Score: 0.3205426774109418


**Result:** worse than the k-means distilbert responses 

### 2. Topics-dataset: stacked responses

In [28]:
mstack = pd.read_json("~/thesis/data/processed_uscensus/political_mentions_stack.jsonl", orient = 'records', lines = True)

In [29]:
mstack

stack
0                  racim blacks whites false information
1                                coming together country
2      severe political polarization allow compromise...
3                                      pandemic covid 19
4      globalism fake covid law order blm public educ...
...                                                  ...
16510                                        immigration
16511  pandemic people wanting comply mask mandate ma...
16512              global position us along around world
16513            attempt take away 2nd ammendment rights
16514  gun control believe country needs move living ...

[16515 rows x 1 columns]

In [30]:
documents = mstack['stack'].to_list()

In [31]:
# Create a Bag of Words model
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(documents)

# Convert to array to see the result
X_array = X.toarray()

# Feature names (words)
features = vectorizer.get_feature_names_out()

print(features)
print(X_array)

['00' '000' '04' ... 'zilch' 'zombie' 'zone']
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [33]:
from sklearn.cluster import KMeans

# Apply KMeans clustering
n_clusters = 4  # Example: trying to find 2 clusters
kmeans = KMeans(n_clusters=n_clusters, random_state=0)
kmeans.fit(X_array)

# Get cluster labels
labels = kmeans.labels_

print(labels)


[0 0 0 ... 0 0 3]


In [34]:
from sklearn.metrics import silhouette_score

# Calculate the silhouette score
sil_score = silhouette_score(X_array, labels)
print(f"Silhouette Score: {sil_score}")


Silhouette Score: 0.035337722201187714


**Result:** worse than the distilbert-kmeans result